version: '3.8'
services:
  kali:
    image: kalictl/kali:latest
    privileged: true
    hostname: kali
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - "NET_ADMIN"
    volumes:
      - ~/.kali:/opt/devstorage:rw
    networks:
      kali-net:
        ipv4_address: 10.0.0.2
  kracker:
    image: kalictl/kracker:latest
    privileged: true
    hostname: kracker
    restart: unless-stopped
    networks:
      kali-net:
        ipv4_address: 10.0.0.3
  penbuntu:
    image: kalictl/penbuntu:latest
    privileged: true
    hostname: penbuntu
    restart: unless-stopped
    networks:
      kali-net:
        ipv4_address: 10.0.0.4

networks:
  kali-net:
    external: true
